// <auto-generated />
using System;
using FormsApp_CS2_Arbitrage_And_Investment_Tracker.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormsApp_CS2_Arbitrage_And_Investment_Tracker.Migrations
{
    [DbContext(typeof(CS2TrackerContext))]
    partial class CS2TrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.DailyStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalDailyInvested")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalDailyProfit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalDailyVolume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyStats");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateBought")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSold")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("SellPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SheetId")
                        .HasColumnType("int");

                    b.Property<int>("SkinInfoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateBought");

                    b.HasIndex("DateSold");

                    b.HasIndex("SheetId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "DateSold");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.OverallStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BuyVolume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SellVolume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TotalHoldDays")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalProfit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OverallStats");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.Sheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SheetType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.SkinInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<float?>("ItemFloat")
                        .HasColumnType("real");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("MarketHashName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkinCondition")
                        .HasColumnType("int");

                    b.Property<int>("SkinVariant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.ToTable("SkinInfos");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.Entry", b =>
                {
                    b.HasOne("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.Sheet", "Sheet")
                        .WithMany("Entries")
                        .HasForeignKey("SheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.Sheet", b =>
                {
                    b.HasOne("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.User", "User")
                        .WithMany("Sheets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.SkinInfo", b =>
                {
                    b.HasOne("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.Entry", "Entry")
                        .WithOne("SkinInfo")
                        .HasForeignKey("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.SkinInfo", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.Entry", b =>
                {
                    b.Navigation("SkinInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.Sheet", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("FormsApp_CS2_Arbitrage_And_Investment_Tracker.Classes.User", b =>
                {
                    b.Navigation("Sheets");
                });
#pragma warning restore 612, 618
        }
    }
}
